//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenSaxanov203
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bd_SaxanovEntities : DbContext
    {
        private static Bd_SaxanovEntities _context;
           
        public Bd_SaxanovEntities()
            : base("name=Bd_SaxanovEntities")
        {
        }
        public static Bd_SaxanovEntities GetContext()
        {
            if (_context == null)
                _context = new Bd_SaxanovEntities();
            return _context;
        }
            
            

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategorii> Kategorii { get; set; }
        public virtual DbSet<Pastovshik> Pastovshik { get; set; }
        public virtual DbSet<Proizvoditel> Proizvoditel { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tovar> Tovar { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
