//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzamenSaxanov203
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Kod_User { get; set; }
        public string Familia_User { get; set; }
        public string Imia_User { get; set; }
        public string Otchestvo_User { get; set; }
        public string Login_User { get; set; }
        public string Parol_User { get; set; }
        public int Role_User { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
